"""create github connections table

Revision ID: 7c9de4c89ae8
Revises: da15b49a2373
Create Date: 2026-08-19 19:42:05.119853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c9de4c89ae8"
down_revision: str | Sequence[str] | None = "da15b49a2373"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_connections",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("github_username", sa.String(), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_connections")
    # ### end Alembic commands ###
